// Insert text and images from data array.
$(function () {
  const data = [
    {
      product: "ULTRA-FRAIS",
      photo: "#N/A",
      description: "#N/A",
      id: 1,
    },
    {
      product: "AUTRES SPECIALITES (dont MDD)",
      photo: 0,
      description:
        "Yaourts à la grecque qui ne sont pas fjord, perle de lait ou yaos (ex : delta frais,…)",
      id: 2,
    },
    {
      product: "FJORD",
      photo: 1,
      description: "FJORD",
      id: 3,
    },
    {
      product: "PERLE DE LAIT BICOUCHE",
      photo: 2,
      description: "PERLE DE LAIT BICOUCHE",
      id: 4,
    },
    {
      product: "PERLE DE LAIT BRASSE",
      photo: 3,
      description: "PERLE DE LAIT BRASSE",
      id: 5,
    },
    {
      product: "PERLE DE LAIT NATURE",
      photo: 4,
      description: "PERLE DE LAIT NATURE",
      id: 6,
    },
    {
      product: "YAOS SPECIALITE BICOUCHE ET MORCEAUX",
      photo: 5,
      description: "YAOS SPECIALITE BICOUCHE ET MORCEAUX",
      id: 7,
    },
    {
      product: "YAOS SPECIALITE BRASSE",
      photo: 6,
      description: "YAOS SPECIALITE BRASSE",
      id: 8,
    },
    {
      product: "YAOS SPECIALITE NATURE HORS GROS POT",
      photo: 7,
      description: "YAOS SPECIALITE NATURE HORS GROS POT",
      id: 9,
    },
    {
      product: "YAOS NATURE GROS POT",
      photo: 8,
      description: "YAOS NATURE GROS POT",
      id: 10,
    },
    {
      product: "UF SOJA",
      photo: "DESCRIPTION",
      description: "Yaourts à base de soja",
      id: 11,
    },
    {
      product: "UF VEGETAL HORS SOJA",
      photo: "DESCRIPTION",
      description: "Yaourts à base de lait végétal (hors soja)",
      id: 12,
    },
    {
      product: "UF CHEVRE ET BREBIS",
      photo: "DESCRIPTION",
      description: "Yaourts chèvre et brebis",
      id: 13,
    },
    {
      product: "DESSERTS QUOTIDIENS",
      photo: 9,
      description: "DESSERTS QUOTIDIENS",
      id: 14,
    },
    {
      product: "DESSERTS PATISSIERS",
      photo: 10,
      description: "DESSERTS PATISSIERS",
      id: 15,
    },
    {
      product: "YOPLAIT SKYR NATURE HORS GROS POT",
      photo: 11,
      description: "YOPLAIT SKYR NATURE HORS GROS POT",
      id: 16,
    },
    {
      product: "YOPLAIT SKYR NATURE GROS POT (>400gr)",
      photo: 12,
      description: "YOPLAIT SKYR NATURE GROS POT (>400gr)",
      id: 17,
    },
    {
      product: "YOPLAIT SKYR ARO HORS GROS POT",
      photo: 13,
      description: "YOPLAIT SKYR ARO HORS GROS POT",
      id: 18,
    },
    {
      product: "YOPLAIT SKYR ARO GROS POT (>400gr)",
      photo: 14,
      description: "YOPLAIT SKYR ARO GROS POT (>400gr)",
      id: 19,
    },
    {
      product: "YOPLAIT SKYR BICOUCHE",
      photo: 15,
      description: "YOPLAIT SKYR BICOUCHE",
      id: 20,
    },
    {
      product: "SIGGI'S NATURE HORS GROS POT",
      photo: 16,
      description: "SIGGI'S NATURE HORS GROS POT",
      id: 21,
    },
    {
      product: "SIGGI'S NATURE GROS POT (>400gr)",
      photo: 17,
      description: "SIGGI'S NATURE GROS POT (>400gr)",
      id: 22,
    },
    {
      product: "SIGGI'S NATURE GROS POT (>400gr)",
      photo: 18,
      description: "SIGGI'S NATURE GROS POT (>400gr)",
      id: 23,
    },
    {
      product: "DANONE SKYR NATURE HORS GROS POT",
      photo: 19,
      description: "DANONE SKYR NATURE HORS GROS POT",
      id: 24,
    },
    {
      product: "DANONE SKYR NATURE GROS POT (>400gr)",
      photo: 20,
      description: "DANONE SKYR NATURE GROS POT (>400gr)",
      id: 25,
    },
    {
      product: "DANONE SKYR ARO",
      photo: 21,
      description: "DANONE SKYR ARO",
      id: 26,
    },
    {
      product: "DANONE SKYR YAB",
      photo: 22,
      description: "DANONE SKYR YAB",
      id: 27,
    },
    {
      product: "DANONE SKYR L'ONCTUEUX NATURE",
      photo: 23,
      description: "DANONE SKYR L'ONCTUEUX NATURE",
      id: 28,
    },
    {
      product: "AUTRES SKYR NATURE",
      photo: 24,
      description: "AUTRES SKYR NATURE",
      id: 29,
    },
    {
      product: "AUTRES SKYR ARO OU BICOUCHE",
      photo: 25,
      description: "AUTRES SKYR ARO OU BICOUCHE",
      id: 30,
    },
    {
      product: "BIFIDUS/DIGESTION FRUIT",
      photo: 26,
      description: "BIFIDUS/DIGESTION FRUIT",
      id: 31,
    },
    {
      product: "BIFIDUS/DIGESTION NATURE",
      photo: 27,
      description: "BIFIDUS/DIGESTION NATURE",
      id: 32,
    },
    {
      product: "YAOURT ANTICHOLESTEROL ou SANS LACTOSE",
      photo: 28,
      description: "YAOURT ANTICHOLESTEROL ou SANS LACTOSE",
      id: 33,
    },
    {
      product: "PANIER DE YOPLAIT ALLEGE",
      photo: 29,
      description: "PANIER DE YOPLAIT ALLEGE",
      id: 34,
    },
    {
      product: "LIGHT & FREE HORS SKYR",
      photo: 30,
      description: "LIGHT & FREE hors skyr",
      id: 35,
    },
    {
      product: "CALIN ALLEGE",
      photo: 31,
      description: "CALIN ALLEGE",
      id: 36,
    },
    {
      product: "SVELTESSE",
      photo: 32,
      description: "SVELTESSE",
      id: 37,
    },
    {
      product: "AUTRES MARQUES ALLEGES (dont MDD)",
      photo: 33,
      description: "AUTRES MARQUES ALLEGES (dont MDD)",
      id: 38,
    },
    {
      product: "ACTIMEL",
      photo: 34,
      description: "ACTIMEL",
      id: 39,
    },
    {
      product: "DANONE HIPRO POT",
      photo: 35,
      description: "DANONE HIPRO POT",
      id: 40,
    },
    {
      product: "DANONE HIPRO YAB",
      photo: 36,
      description: "DANONE HIPRO YAB",
      id: 41,
    },
    {
      product: "DANONE HIPRO DESSERT",
      photo: 37,
      description: "DANONE HIPRO DESSERT",
      id: 42,
    },
    {
      product: "LINDAHL'S POT",
      photo: 38,
      description: "LINDAHL'S POT",
      id: 43,
    },
    {
      product: "YAB PROTEINES (ex LINDAHL'S )",
      photo: 39,
      description: "YAB PROTEINES (ex LINDAHL'S )",
      id: 44,
    },
    {
      product: "LINDAHL'S DESSERT",
      photo: 40,
      description: "LINDAHL'S DESSERT",
      id: 45,
    },
    {
      product: "AUTRES MARQUES PROTEINES (DONT MDD) POT",
      photo: 41,
      description: "AUTRES MARQUES PROTEINES (DONT MDD) POT",
      id: 46,
    },
    {
      product: "VELOUTE YAOURT FRUITS MIXES",
      photo: 42,
      description: "VELOUTE YAOURT FRUITS MIXES",
      id: 47,
    },
    {
      product: "PANIER DE YOPLAIT 100% MORCEAUX DE FRUITS",
      photo: 43,
      description: "PANIER DE YOPLAIT 100% MORCEAUX DE FRUITS",
      id: 48,
    },
    {
      product: "PANIER DE YOPLAIT NATURE SUR FRUITS",
      photo: 44,
      description: "PANIER DE YOPLAIT NATURE SUR FRUITS",
      id: 49,
    },
    {
      product: "LA LAITIERE POT VERRE FRUIT",
      photo: 45,
      description: "LA LAITIERE POT VERRE FRUIT",
      id: 50,
    },
    {
      product: "AUTRES POT VERRE FRUIT",
      photo: 46,
      description:
        "Yaourt aux fruits avec pot en verre en dehors de La Laitière",
      id: 51,
    },
    {
      product: "AUTRES YAOURT FRUITS STD",
      photo: 47,
      description:
        "Yaourt aux fruits classiques (hors velouté et hors Panier de Yoplait)",
      id: 52,
    },
    {
      product: "MAMIE NOVA YAOURT GOURMAND",
      photo: 48,
      description: "MAMIE NOVA YAOURT GOURMAND",
      id: 53,
    },
    {
      product: "YOP BOUTEILLES ADO",
      photo: 49,
      description: "YOP BOUTEILLES ADO",
      id: 54,
    },
    {
      product: "AUTRES BOUTEILLES ADO (dont MDD)",
      photo: 50,
      description:
        "Yaourt à boire en bouteilles pour adolescents hors Yop",
      id: 55,
    },
    {
      product: "CAFE LATTE  (starbucks…)",
      photo: 51,
      description: "CAFE LATTE  (starbucks…)",
      id: 56,
    },
    {
      product: "AUTRES BOUTEILLES ADULTES",
      photo: 52,
      description:
        "Yaourt à boire en bouteilles pour adulte en dehors des cafés lattes, de YOP, et de Hipro",
      id: 57,
    },
    {
      product: "PETITS FILOUS DESSERT",
      photo: 53,
      description: "PETITS FILOUS DESSERT",
      id: 58,
    },
    {
      product: "PETITS FILOUS ENFANT DEAMBULATOIRE",
      photo: 54,
      description: "PETITS FILOUS ENFANT DEAMBULATOIRE",
      id: 59,
    },
    {
      product: "PETITS FILOUS ENFANT POT",
      photo: 55,
      description: "PETITS FILOUS ENFANT POT",
      id: 60,
    },
    {
      product: "PETITS FILOUS ENFANT YAOURT A BOIRE",
      photo: 56,
      description: "PETITS FILOUS ENFANT YAOURT A BOIRE",
      id: 61,
    },
    {
      product: "P'TIT YOP ENFANT YAOURT A BOIRE",
      photo: 57,
      description: "P'TIT YOP ENFANT YAOURT A BOIRE",
      id: 62,
    },
    {
      product: "MINI YOP ENFANT YAOURT A BOIRE",
      photo: 58,
      description: "MINI YOP ENFANT YAOURT A BOIRE",
      id: 63,
    },
    {
      product: "YOPLAIT POT PAT PATROUILLE",
      photo: 59,
      description: "YOPLAIT POT PAT PATROUILLE",
      id: 65,
    },
    {
      product: "FLANBY ENFANT DESSERT",
      photo: 60,
      description: "FLANBY ENFANT DESSERT",
      id: 66,
    },
    {
      product: "FRULOS ENFANT POT",
      photo: 61,
      description: "FRULOS ENFANT POT",
      id: 67,
    },
    {
      product: "KINDER PINGUI",
      photo: 62,
      description: "KINDER PINGUI",
      id: 68,
    },
    {
      product: "NESQUIK PETIT",
      photo: 63,
      description: "NESQUIK PETIT",
      id: 69,
    },
    {
      product: "NESTLE ENFANT POT (SMARTIES, KITKAT)",
      photo: 64,
      description: "NESTLE ENFANT POT (SMARTIES, KITKAT)",
      id: 70,
    },
    {
      product: "DANONINO ENFANT POT",
      photo: 65,
      description: "DANONINO ENFANT POT",
      id: 71,
    },
    {
      product: "DANONINO ENFANT NOMADE",
      photo: 66,
      description: "DANONINO ENFANT NOMADE",
      id: 72,
    },
    {
      product: "DANONINO ENFANT YAOURT A BOIRE",
      photo: 67,
      description: "DANONINO ENFANT YAOURT A BOIRE",
      id: 73,
    },
    {
      product: "DANETTE ENFANT",
      photo: 68,
      description: "DANETTE ENFANT",
      id: 74,
    },
    {
      product: "AUTRES ENFANT DESSERT",
      photo: 69,
      description: "Crèmes desserts pour enfants hors danette",
      id: 75,
    },
    {
      product: "AUTRES ENFANT POT",
      photo: 70,
      description: "AUTRES ENFANT POT",
      id: 76,
    },
    {
      product: "AUTRES ENFANT YAOURT A BOIRE 131-185g",
      photo: 71,
      description: "AUTRES ENFANT YAOURT A BOIRE 131-185g",
      id: 77,
    },
    {
      product: "AUTRES ENFANT YAOURT A BOIRE <=100G",
      photo: 72,
      description: "AUTRES ENFANT YAOURT A BOIRE <=100G",
      id: 78,
    },
    {
      product: "PETIT YOPLAIT SUISSE",
      photo: 73,
      description: "PETIT YOPLAIT SUISSE",
      id: 79,
    },
    {
      product: "GERVAIS LE YAOURT SUISSE",
      photo: 74,
      description: "GERVAIS LE YAOURT SUISSE",
      id: 80,
    },
    {
      product: "AUTRES FROMAGE BLANC GROS POT (>400gr)",
      photo: 75,
      description: "AUTRES FROMAGE BLANC GROS POT (>400gr)",
      id: 81,
    },
    {
      product: "AUTRES FROMAGE BLANC HORS GROS POT",
      photo: 76,
      description: "AUTRES FROMAGE BLANC HORS GROS POT",
      id: 82,
    },
    {
      product: "DANONE FROMAGE BLANC GROS POT (>400gr)",
      photo: 77,
      description: "DANONE FROMAGE BLANC GROS POT (>400gr)",
      id: 83,
    },
    {
      product: "DANONE FROMAGE BLANC HORS GROS POT",
      photo: 78,
      description: "DANONE FROMAGE BLANC HORS GROS POT",
      id: 84,
    },
    {
      product: "CALIN FROMAGE BLANC GROS POT (>400gr )",
      photo: 79,
      description: "CALIN FROMAGE BLANC GROS POT (>400gr )",
      id: 85,
    },
    {
      product: "CALIN FROMAGE BLANC HORS GROS POT",
      photo: 80,
      description: "CALIN FROMAGE BLANC HORS GROS POT",
      id: 86,
    },
    {
      product: "JOCKEY FROMAGE BLANC",
      photo: 81,
      description: "JOCKEY FROMAGE BLANC",
      id: 87,
    },
    {
      product: "VELOUTE NATURE",
      photo: 82,
      description: "VELOUTE NATURE",
      id: 88,
    },
    {
      product: "YOPLAIT NATURE SUCRE",
      photo: 83,
      description: "YOPLAIT NATURE SUCRE",
      id: 89,
    },
    {
      product: "DANONE STANDARD",
      photo: 84,
      description: "DANONE STANDARD",
      id: 90,
    },
    {
      product: "AUTRES YAOURTS NATURES",
      photo: 85,
      description: "Yaourt nature avec pot en verre",
      id: 91,
    },
    {
      product: "YOPLAIT EN BRIQUE",
      photo: 86,
      description: "YOPLAIT EN BRIQUE",
      id: 92,
    },
    {
      product: "AROMATISE",
      photo: 87,
      description: "Yaourt aromatisé",
      id: 93,
    },
    {
      product: "COMPOTE EPICERIE GOURDE",
      photo: "DESCRIPTION",
      description: "Compote au rayon ambiant en gourde",
      id: 94,
    },
    {
      product: "LAIT SANS LACTOSE",
      photo: "DESCRIPTION",
      description: "Lait sans lactose",
      id: 95,
    },
    {
      product: "CANDY UP",
      photo: 88,
      description: "CANDY UP",
      id: 96,
    },
    {
      product: "CREME FRAICHE",
      photo: "DESCRIPTION",
      description: "Crème fraiche",
      id: 97,
    },
    {
      product: "CREME UHT",
      photo: "DESCRIPTION",
      description: "Crème UHT",
      id: 98,
    },
    {
      product: "LAIT FERMENTE hors KEFIR",
      photo: "DESCRIPTION",
      description: "Lait fermenté hors Kéfir",
      id: 99,
    },
    {
      product: "KEFIR",
      photo: "DESCRIPTION",
      description: "Kéfir",
      id: 100,
    },
    {
      product: "COMPOTE EPICERIE POT",
      photo: "DESCRIPTION",
      description: "Compote au rayon ambiant en pot",
      id: 101,
    },
    {
      product: "LAIT LONGUE CONSERVATION",
      photo: "DESCRIPTION",
      description: "Lait longue conservation",
      id: 102,
    },
    {
      product: "COMPOTE FRAICHE POT",
      photo: "DESCRIPTION",
      description: "Compote au rayon frais en pot",
      id: 103,
    },
    {
      product: "FROMAGE ENFANT",
      photo: "DESCRIPTION",
      description: "Fromage enfant",
      id: 104,
    },
  ];

  const Q7_2Items = [
    {
      name: "PERLE DE LAIT BICOUCHE",
      flag: "%[flag]Q277_4%",
      id: 4,
    },
    {
      name: "PERLE DE LAIT BRASSE",
      flag: "%[flag]Q277_5%",
      id: 5,
    },
    {
      name: "PERLE DE LAIT NATURE",
      flag: "%[flag]Q277_6%",
      id: 6,
    },
    {
      name: "YOPLAIT SKYR NATURE",
      flag: "%[flag]Q277_16%",
      id: 16,
    },
    {
      name: "YOPLAIT SKYR ARO",
      flag: "%[flag]Q277_18%",
      id: 18,
    },
    {
      name: "YOPLAIT SKYR BICOUCHE",
      flag: "%[flag]Q277_20%",
      id: 20,
    },
    {
      name: "PANIER DE YOPLAIT ALLEGE",
      flag: "%[flag]Q277_34%",
      id: 34,
    },
    {
      name: "PANIER DE YOPLAIT 100% MORCEAUX DE FRUITS",
      flag: "%[flag]Q277_48%",
      id: 48,
    },
    {
      name: "PANIER DE YOPLAIT NATURE SUR FRUITS",
      flag: "%[flag]Q277_49%",
      id: 49,
    },
    {
      name: "CALIN ALLEGE",
      flag: "%[flag]Q277_35%",
      id: 35,
    },
    {
      name: "CALIN FROMAGE BLANC",
      flag: "%[flag]Q277_85%",
      id: 85,
    },
    {
      name: "PETITS FILOUS DESSERT",
      flag: "%[flag]Q277_58%",
      id: 58,
    },
    {
      name: "PETITS FILOUS ENFANT DEAMBULATOIRE",
      flag: "%[flag]Q277_59%",
      id: 59,
    },
    {
      name: "PETITS FILOUS ENFANT POT",
      flag: "%[flag]Q277_60%",
      id: 60,
    },
    {
      name: "PETITS FILOUS ENFANT YAOURT A BOIRE",
      flag: "%[flag]Q277_61%",
      id: 61,
    },
    {
      name: "YOP BOUTEILLES ADO",
      flag: "%[flag]Q277_54%",
      id: 54,
    },
    {
      name: "YOP ENFANT YAOURT A BOIR",
      flag: "%[flag]Q277_62%",
      id: 62,
    },
  ];

  const images = [
    '<img src="%[IMG]Q264_1%" width="150" >',
    '<img src="%[IMG]Q264_2%" width="150" >',
    '<img src="%[IMG]Q264_3%" width="150" >',
    '<img src="%[IMG]Q264_4%" width="150" >',
    '<img src="%[IMG]Q264_5%" width="150" >',
    '<img src="%[IMG]Q264_6%" width="150" >',
    '<img src="%[IMG]Q264_7%" width="150" >',
    '<img src="%[IMG]Q264_8%" width="150" >',
    '<img src="%[IMG]Q264_9%" width="150" >',
    '<img src="%[IMG]Q264_10%" width="150" >',
    '<img src="%[IMG]Q264_11%" width="150" >',
    '<img src="%[IMG]Q264_12%" width="150" >',
    '<img src="%[IMG]Q264_13%" width="150" >',
    '<img src="%[IMG]Q264_14%" width="150" >',
    '<img src="%[IMG]Q264_15%" width="150" >',
    '<img src="%[IMG]Q264_16%" width="150" >',
    '<img src="%[IMG]Q264_17%" width="150" >',
    '<img src="%[IMG]Q264_18%" width="150" >',
    '<img src="%[IMG]Q264_19%" width="150" >',
    '<img src="%[IMG]Q264_20%" width="150" >',
    '<img src="%[IMG]Q264_21%" width="150" >',
    '<img src="%[IMG]Q264_22%" width="150" >',
    '<img src="%[IMG]Q264_23%" width="150" >',
    '<img src="%[IMG]Q264_24%" width="150" >',
    '<img src="%[IMG]Q264_25%" width="150" >',
    '<img src="%[IMG]Q264_26%" width="150" >',
    '<img src="%[IMG]Q264_27%" width="150" >',
    '<img src="%[IMG]Q264_28%" width="150" >',
    '<img src="%[IMG]Q264_29%" width="150" >',
    '<img src="%[IMG]Q264_30%" width="150" >',
    '<img src="%[IMG]Q264_31%" width="150" >',
    '<img src="%[IMG]Q264_32%" width="150" >',
    '<img src="%[IMG]Q264_33%" width="150" >',
    '<img src="%[IMG]Q264_34%" width="150" >',
    '<img src="%[IMG]Q264_35%" width="150" >',
    '<img src="%[IMG]Q264_36%" width="150" >',
    '<img src="%[IMG]Q264_37%" width="150" >',
    '<img src="%[IMG]Q264_38%" width="150" >',
    '<img src="%[IMG]Q264_39%" width="150" >',
    '<img src="%[IMG]Q264_40%" width="150" >',
    '<img src="%[IMG]Q264_41%" width="150" >',
    '<img src="%[IMG]Q264_42%" width="150" >',
    '<img src="%[IMG]Q264_43%" width="150" >',
    '<img src="%[IMG]Q264_44%" width="150" >',
    '<img src="%[IMG]Q264_45%" width="150" >',
    '<img src="%[IMG]Q264_46%" width="150" >',
    '<img src="%[IMG]Q264_47%" width="150" >',
    '<img src="%[IMG]Q264_48%" width="150" >',
    '<img src="%[IMG]Q264_49%" width="150" >',
    '<img src="%[IMG]Q264_50%" width="150" >',
    '<img src="%[IMG]Q264_51%" width="150" >',
    '<img src="%[IMG]Q264_52%" width="150" >',
    '<img src="%[IMG]Q264_53%" width="150" >',
    '<img src="%[IMG]Q264_54%" width="150" >',
    '<img src="%[IMG]Q264_55%" width="150" >',
    '<img src="%[IMG]Q264_56%" width="150" >',
    '<img src="%[IMG]Q264_57%" width="150" >',
    '<img src="%[IMG]Q264_58%" width="150" >',
    '<img src="%[IMG]Q264_59%" width="150" >',
    '<img src="%[IMG]Q264_60%" width="150" >',
    '<img src="%[IMG]Q264_61%" width="150" >',
    '<img src="%[IMG]Q264_62%" width="150" >',
    '<img src="%[IMG]Q264_63%" width="150" >',
    '<img src="%[IMG]Q264_64%" width="150" >',
    '<img src="%[IMG]Q264_65%" width="150" >',
    '<img src="%[IMG]Q264_66%" width="150" >',
    '<img src="%[IMG]Q264_67%" width="150" >',
    '<img src="%[IMG]Q264_68%" width="150" >',
    '<img src="%[IMG]Q264_69%" width="150" >',
    '<img src="%[IMG]Q264_70%" width="150" >',
    '<img src="%[IMG]Q264_71%" width="150" >',
    '<img src="%[IMG]Q264_72%" width="150" >',
    '<img src="%[IMG]Q264_73%" width="150" >',
    '<img src="%[IMG]Q264_74%" width="150" >',
    '<img src="%[IMG]Q264_75%" width="150" >',
    '<img src="%[IMG]Q264_76%" width="150" >',
    '<img src="%[IMG]Q264_77%" width="150" >',
    '<img src="%[IMG]Q264_78%" width="150" >',
    '<img src="%[IMG]Q264_79%" width="150" >',
    '<img src="%[IMG]Q264_80%" width="150" >',
    '<img src="%[IMG]Q264_81%" width="150" >',
    '<img src="%[IMG]Q264_82%" width="150" >',
    '<img src="%[IMG]Q264_83%" width="150" >',
    '<img src="%[IMG]Q264_84%" width="150" >',
    '<img src="%[IMG]Q264_85%" width="150" >',
    '<img src="%[IMG]Q264_86%" width="150" >',
    '<img src="%[IMG]Q264_87%" width="150" >',
    '<img src="%[IMG]Q264_88%" width="150" >',
    '<img src="%[IMG]Q264_89%" width="150" >',
    '<img src="%[IMG]Q264_90%" width="150" >',
  ];

  console.log("Q7_2Items:", Q7_2Items);
  console.log("Images:", images);

  let row = 1;
  Q7_2Items.forEach(Q7item => {
    if (Q7item.flag == "1") {
      const productData = data.find((item) => item.id === Q7item.id);
      if (productData) {
        console.log("Row:", row, "productData:", productData);
        $(`#${row}_name`).text(productData.product);
        $(`#${row}_img`).html(images[productData.photo]);
      } else {
        $(`#${row}_name`).parent().html("");
      }
      row++;
    }
  });
});
